-- MySQL Script generated by MySQL Workbench
-- Mon May 18 16:27:58 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydbBiblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydbBiblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydbBiblioteca` DEFAULT CHARACTER SET utf8 ;
USE `mydbBiblioteca` ;

-- -----------------------------------------------------
-- Table `mydbBiblioteca`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbBiblioteca`.`Pais` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `PaisDescripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idPais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbBiblioteca`.`Editorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbBiblioteca`.`Editorial` (
  `idEditorial` INT NOT NULL AUTO_INCREMENT,
  `EditorialDescripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idEditorial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbBiblioteca`.`Coleccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbBiblioteca`.`Coleccion` (
  `idColeccion` INT NOT NULL,
  `ColeccionDescripcion` VARCHAR(45) NULL,
  `NumeroTomos` INT NULL,
  PRIMARY KEY (`idColeccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbBiblioteca`.`Libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbBiblioteca`.`Libro` (
  `idLibro` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(100) NULL,
  `Numero` INT NULL,
  `Paginas` INT NULL,
  `FechaPublicacion` DATE NULL,
  `ISBN` VARCHAR(45) NULL,
  `LinkImagen` VARCHAR(200) NULL,
  `LinkDescarga` VARCHAR(200) NULL,
  `CantidadVecesPedidas` INT NULL,
  `Estado` INT NULL,
  `Pais_idPais` INT NOT NULL,
  `Editorial_idEditorial` INT NOT NULL,
  `Coleccion_idColeccion` INT NOT NULL,
  `Coleccion_idColeccion1` INT NOT NULL,
  PRIMARY KEY (`idLibro`),
  INDEX `fk_Libro_Pais_idx` (`Pais_idPais` ASC) VISIBLE,
  INDEX `fk_Libro_Editorial1_idx` (`Editorial_idEditorial` ASC) VISIBLE,
  INDEX `fk_Libro_Coleccion1_idx` (`Coleccion_idColeccion1` ASC) VISIBLE,
  CONSTRAINT `fk_Libro_Pais`
    FOREIGN KEY (`Pais_idPais`)
    REFERENCES `mydbBiblioteca`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libro_Editorial1`
    FOREIGN KEY (`Editorial_idEditorial`)
    REFERENCES `mydbBiblioteca`.`Editorial` (`idEditorial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libro_Coleccion1`
    FOREIGN KEY (`Coleccion_idColeccion1`)
    REFERENCES `mydbBiblioteca`.`Coleccion` (`idColeccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbBiblioteca`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbBiblioteca`.`Genero` (
  `idGenero` INT NOT NULL AUTO_INCREMENT,
  `GeneroDescripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idGenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbBiblioteca`.`Libro_has_Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbBiblioteca`.`Libro_has_Genero` (
  `Libro_idLibro` INT NOT NULL,
  `Genero_idGenero` INT NOT NULL,
  INDEX `fk_Libro_has_genero_Genero1_idx` (`Genero_idGenero` ASC) VISIBLE,
  INDEX `fk_Libro_has_genero_Libro1_idx` (`Libro_idLibro` ASC) VISIBLE,
  CONSTRAINT `fk_Libro_has_genero_Genero1`
    FOREIGN KEY (`Genero_idGenero`)
    REFERENCES `mydbBiblioteca`.`Genero` (`idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libro_has_genero_Libro1`
    FOREIGN KEY (`Libro_idLibro`)
    REFERENCES `mydbBiblioteca`.`Libro` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbBiblioteca`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbBiblioteca`.`Autor` (
  `idAutor` INT NOT NULL AUTO_INCREMENT,
  `AutorDescripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbBiblioteca`.`Libro_has_Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbBiblioteca`.`Libro_has_Autor` (
  `Autor_idAutor` INT NOT NULL,
  `Libro_idLibro` INT NOT NULL,
  INDEX `fk_Libro_has_Autor_Libro1_idx` (`Libro_idLibro` ASC) VISIBLE,
  INDEX `fk_Libro_has_Autor_Autor1_idx` (`Autor_idAutor` ASC) VISIBLE,
  CONSTRAINT `fk_Libro_has_Autor_Libro1`
    FOREIGN KEY (`Libro_idLibro`)
    REFERENCES `mydbBiblioteca`.`Libro` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libro_has_Autor_Autor1`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `mydbBiblioteca`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbBiblioteca`.`Permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbBiblioteca`.`Permisos` (
  `idPermisos` INT NOT NULL AUTO_INCREMENT,
  `PermisoCrearSocio` INT NULL,
  `PermisoCrearLibro` INT NULL,
  PRIMARY KEY (`idPermisos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbBiblioteca`.`TipoPerfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbBiblioteca`.`TipoPerfil` (
  `idTipoPerfil` INT NOT NULL AUTO_INCREMENT,
  `PerfilDescripcion` VARCHAR(45) NULL,
  `Permisos_idPermisos` INT NOT NULL,
  PRIMARY KEY (`idTipoPerfil`),
  INDEX `fk_TipoPerfil_Permisos1_idx` (`Permisos_idPermisos` ASC) VISIBLE,
  CONSTRAINT `fk_TipoPerfil_Permisos1`
    FOREIGN KEY (`Permisos_idPermisos`)
    REFERENCES `mydbBiblioteca`.`Permisos` (`idPermisos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbBiblioteca`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbBiblioteca`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `FechaRegistro` DATE NULL,
  `TipoPerfil_idTipoPerfil` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_TipoPerfil1_idx` (`TipoPerfil_idTipoPerfil` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_TipoPerfil1`
    FOREIGN KEY (`TipoPerfil_idTipoPerfil`)
    REFERENCES `mydbBiblioteca`.`TipoPerfil` (`idTipoPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbBiblioteca`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbBiblioteca`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Sexo` VARCHAR(45) NULL,
  `Dni` INT NULL,
  `Cuil` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPersona`),
  INDEX `fk_Persona_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Persona_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydbBiblioteca`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbBiblioteca`.`FichaSocioBiblioteca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbBiblioteca`.`FichaSocioBiblioteca` (
  `idFichaSocioBiblioteca` INT NOT NULL AUTO_INCREMENT,
  `FechaInicio` DATE NULL,
  `FechaFin` DATE NULL,
  `TipoSocio` VARCHAR(45) NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idFichaSocioBiblioteca`),
  INDEX `fk_FichaSocioBiblioteca_Persona1_idx` (`Persona_idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_FichaSocioBiblioteca_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydbBiblioteca`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbBiblioteca`.`Prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbBiblioteca`.`Prestamo` (
  `idPrestamo` INT NOT NULL AUTO_INCREMENT,
  `FechaPrestamo` DATE NULL,
  `FechaEntrega` DATE NULL,
  `FechaDevolucion` DATE NULL,
  `FichaSocioBiblioteca_idFichaSocioBiblioteca` INT NOT NULL,
  `Libro_idLibro` INT NOT NULL,
  PRIMARY KEY (`idPrestamo`),
  INDEX `fk_Prestamo_Libro1_idx` (`Libro_idLibro` ASC) VISIBLE,
  INDEX `fk_Prestamo_FichaSocioBiblioteca1_idx` (`FichaSocioBiblioteca_idFichaSocioBiblioteca` ASC) VISIBLE,
  CONSTRAINT `fk_Prestamo_Libro1`
    FOREIGN KEY (`Libro_idLibro`)
    REFERENCES `mydbBiblioteca`.`Libro` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestamo_FichaSocioBiblioteca1`
    FOREIGN KEY (`FichaSocioBiblioteca_idFichaSocioBiblioteca`)
    REFERENCES `mydbBiblioteca`.`FichaSocioBiblioteca` (`idFichaSocioBiblioteca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
